#!/usr/bin/env bash
############################################################################
# boards/sim/sim/sim/configs/citest/run
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.  The
# ASF licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#
############################################################################

set -e
set -o xtrace

source /github/workspace/nuttx-ntfc/venv/bin/activate

testpath=/github/workspace/nuttx-ntfc/external/nuttx-testing
board=/github/workspace/sources/nuttx/boards/sim/sim/sim/configs/citest
confpath=${board}/config.yaml
jsonconf=${board}/session.json
python3 -m ntfc test --confpath=${confpath} --testpath=${testpath} --jsonconf=${jsonconf}

ret="$?"
echo $ret

deactivate

# export test results
mv pytest.debug.log /github/workspace/sources/buildartifacts
mv result /github/workspace/sources/buildartifacts

exit $ret
